version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
#      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
#      - nvm install node
      - curl -o- -L https://slss.io/install | bash
      - cat ~/.bashrc
      - source ~/.bashrc
      - cat ~/.bashrc
  build:
    commands:
#      - serverless
      - /bin/bash echo "Hiii"
      - /bin/bash serverless -v
      - sls deploy -v
#      - sam package --template-file template.yaml --s3-bucket sag-kathe-bucket --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
