version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
#      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
#      - nvm install node
      - curl -o- -L https://slss.io/install | bash
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - sudo apt install nodejs
      - . ~/.bashrc
      - node --version
  build:
    commands:
      - echo "Hiii"
      - sls deploy -s dev --verbose
#      - sam package --template-file template.yaml --s3-bucket sag-kathe-bucket --output-template-file packaged-template.yml
