version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - curl -o- -L https://slss.io/install | bash
      - sls deploy -v
#      - sam package --template-file template.yaml --s3-bucket sag-kathe-bucket --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml