org: sagkathe
app: aws-python-project
service: aws-python-project

frameworkVersion: '2'

plugins:
  - serverless-step-functions

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello


stepFunctions:
  stateMachines:
    SampleStepFunction:
      name: HellowWorld-serverless
      definition:
        StartAt: FIRST_STEP
        States:
          FIRST_STEP:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-hello
            End: True
