org: sagkathe
app: aws-python-project
service: aws-python-project

frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello


resources:
  Resources:
    SampleStepFunction:
      Type: AWS::StepFunctions::StateMachine
      Properties:
        StateMachineName: HellowWorld-serverless
        DefinationString: |-
          {
            "StartAt": "HelloWorld",
            "States": {
              "HelloWorld": {
              "Type": "Task",
              "Resource": "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-hello",
              "End": true
              }
            }
          }
